### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by dancarasco** [chrisguttandin/standardized-audio-context#1008]
Hi,

**System**: Apple M2 Max (Macbook Pro) Ventura 13.5.2 (22G91)
**Browser**: Google Chrome 119.0.6045.123 (Official Build) (arm64) / Safari 16.6 (18615.3.12.11.2)
**Technologies**: Vite/Vue3 (latest), standardized-audio-context (latest), ToneJS (latest)

I've encountered this warning in my app today which I have not seen previously. On the **standardized-audio-context-demo** page, two AudioContext warnings appear (Macbook Pro M2, Chrome):

<img width="1701" alt="Screenshot 2023-11-10 at 17 36 57" src="https://github.com/chrisguttandin/standardized-audio-context/assets/49026110/0950c315-6b13-461d-b572-0c51f469c26a">

----
On Safari on the same system, these do not appear:

<img width="1316" alt="Screenshot 2023-11-10 at 17 37 16" src="https://github.com/chrisguttandin/standardized-audio-context/assets/49026110/8d78f658-4d94-48e8-a0a4-2d2864774df3">

---
And I am seeing the same warnings in my app:

<img width="1282" alt="Screenshot 2023-11-10 at 17 46 11" src="https://github.com/chrisguttandin/standardized-audio-context/assets/49026110/a7559598-95db-4afc-8fc0-625ec4a49705">

---
This is simply from importing and creating an AudioContext like so:

```
import { AudioContext, OfflineAudioContext } from 'standardized-audio-context';
const audioContext = new AudioContext();
````

I can only assume policies are stricter with Mac + Chrome as this is occurring as soon as the context is created without user interaction. A library like ToneJS automatically creates a context upon import, so I have no way of easily controlling this via a user interaction.

Please let me know if I'm missing something, as I haven't changed anything recently and this has started occurring.

**Comment by dancarasco** [comment]
Update: Tested on same version of Chrome on Ubuntu and received same warnings.

**Comment by chrisguttandin** [comment]
Hi @dancarasco, thanks for this detailed report. Unfortunately there is no way I'm aware of to avoid these warnings. As you already mentioned a warning appears in the console whenever you do `new AudioContext()` outside of a user interaction. The problem is that this could be a developer error but it doesn't have to be an error. It's perfectly valid to create an `AudioContext` first to resume it later on. Chrome can't tell if creating an `AudioContext`  was done to play something immediately or not. It just warns all the time.

`standardized-audio-context` creates an `AudioContext` to check browser support of a few features. It sometimes creates a `ScriptProcessorNode`, too. That triggers yet another of those warnings.

After all these are only warnings and don't influence the runtime performance.
