### ISSUE TITLE
createMediaElementSource is not a function

### ISSUE THREAD

**Issue by vasinl124** [chrisguttandin/standardized-audio-context#264]
<img width="699" alt="screen shot 2018-03-13 at 1 50 27 pm" src="https://user-images.githubusercontent.com/6901435/37366295-af57e830-26c5-11e8-8782-d3067dab628f.png">
It works with window.AudioContext. I'm not sure this is might be a bug or not.

Thanks,

**Comment by chrisguttandin** [comment]
Hi @vasinl124, it's not really a bug. As I mentioned in the README it's not implemented yet. Mainly just because no one missed it so far. However I need it myself now as well and will probably implement it within the next week.

If that's too late for you, I'm also happy to accept a pull request. Let me know if you want to know how I structure the tests for every feature I add. I can imagine that this is not very obvious.

**Comment by chrisguttandin** [comment]
hi @vasinl124, createMediaElementSource() is now supported in version 11.4.0.

**Comment by vasinl124** [comment]
Oh wow, you are so fast... thank you :)
