### ISSUE TITLE
PannerNode implementation

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#444]
You mention in the README that if people need this feature to add an issue: 🙋🏻‍♂️I need this interface! does not need to necessarily be complete, i understand that the latest spec (which some browsers haven't implemented) has many more AudioParam's than older versions which would be difficult to wrap, so i understand if it's not completely functionally equivalent. i'd be happy to be limited to setPosition/setOrientation unless you've got a clever way to add all of those schedule-able AudioParam.

**Comment by chrisguttandin** [comment]
Yes, I definitely want to add support for the PannerNode. I plan to use a similar technique that I used for the [AudioListener](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/audio-listener-factory.ts). It simulates the AudioParams with a couple of ConstantSourceNodes and sets the new value with the help of a ScriptProcessorNode.

This means that the precision of calling setPosition/setOrientation is only 256 samples. But it is probably not much higher in those browsers anyway.

But feel free to propose something different. I'm not sure if what I've planned is the best solution.

**Comment by tambien** [comment]
i think that resolution for setPosition/Orientation is totally fine. i also can't think of any better way to go about setting the values than a ScriptProcessorNode and i think your technique of using a single ScriptProcessor for multiple params is smart to save processing which is my only concern with the technique.

**Comment by chrisguttandin** [comment]
Hi @tambien, I started with the implementation of the PannerNode. Unfortunately I discovered that Edge does not support HRTF. I already added an expectation test to monitor that: [bug #123](https://github.com/chrisguttandin/standardized-audio-context/blob/master/test/expectation/edge/audio-context-constructor.js#L775). I also found a [uservoice page](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13678635-support-hrtf-for-the-pannernode-interface-in-the-w) which kind of confirms it.

I don't know of a way to polyfill HRTF support. Do you have an idea how that could be done? I would otherwise restrict the panningModel to equalpower for all browsers to achieve a consistent behavior. That's unfortunate but I already used a similar strategy for the [AudioWorklet](https://github.com/chrisguttandin/standardized-audio-context#audioworklet) and the [StereoPanner](https://github.com/chrisguttandin/standardized-audio-context#stereopannernode--createstereopanner).

**Comment by tambien** [comment]
Thanks for looking into that. i agree polyfilling HRTF would be extremely complicated. Personally, my first priority would be standard API and second priority would be consistent behavior. 

Especially in this situation, i think HRTF is a widely used feature of the PannerNode (for me personally) and would love to have it when available and graceful fallback to equalpower when not available.

**Comment by chrisguttandin** [comment]
Thanks for your input.

I choose to throw a NotSupportedError in Edge when someone tries to use HRTF as the panningModel. I think it's better to notify the developer that it doesn't work instead of failing silently. One can still choose to ignore it by doing something like this:

```javascript
const pannerNode = new PannerNode(audioContext);

try {
    pannerNode.panningModel = 'HRTF';
} catch (err) {
    if (err.name !== 'NotSupportedError') {
        throw err;
    }
}
```

Does that work for your use cases?

**Comment by tambien** [comment]
totally! i think that's a good solution

**Comment by chrisguttandin** [comment]
Version 17.6.0 contains an implementation of the PannerNode. Please let me know if you discover any edge cases.
