### ISSUE TITLE
Remove 'window' from browsernizr.ts

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#631]
It looks like you've gone to great care to make sure that you don't use the 'window' variable. This is helpful for me since some users of Tone.js want to be able to load it (or something that depends on it) from within Node.js without throwing errors. 

There is still one reference to the window variable [in this file](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/browsernizr.ts). 

I tried to replace it with your 'createWindow' function, but it looks like that file that i linked is automatically generated in the build process. 

I think you could make a case for removing Modernizr altogether since the main test that you need is 'has WebAudio' which at least in all recent implementations assumes 'has Promise' and 'has TypedArray' since those have been written into the spec for a few years.

It'd also be great to add a simple test which just opens the build in Node.js to see if it throws an error. Something as simple as this: `node -p "require('./')"` might even do it if you check for Errors in the return value. 

Thanks for the great library! Starting to integrate this into Tone.js, so i might have some more questions or issues that pop up in the process.

**Comment by chrisguttandin** [comment]
Hi Yotam,

thanks for pointing this out. Removing this file was on my todo list for a long time. But it wasn't my top priority since I thought it's redundant but also not causing any issues.

I also added a test which loads the library on Node.js and calls `isSupported()` which is of course supposed to return false.

The changes will be included in the next major release which I have to publish anyway because of this breaking change: https://github.com/chrisguttandin/standardized-audio-context/commit/aac367c8c33a07ba2173537bb41b78a8625180b1.

**Comment by tambien** [comment]
@chrisguttandin  thank you!
