### ISSUE TITLE
Mixing audio buffers as one

### ISSUE THREAD

**Issue by rmallick6806** [chrisguttandin/standardized-audio-context#884]
Is it possible to combine audio buffers (guitars and drums) into one to generate a single audio file? Great work on this by the way.

**Comment by chrisguttandin** [comment]
Hi Ray, it is definitely possible to do that. I answered [your question on Stack Overflow](https://stackoverflow.com/questions/61293831/is-there-a-way-to-download-an-audio-file-of-all-the-audio-streams-playing-on-a-p). But I will close the issue here since I believe it is not about a bug of this library. Please let me know if I'm wrong.

**Comment by rmallick6806** [comment]
@chrisguttandin Thank you for your fast response, especially to stackoverflow. I will test it out over there!
