### ISSUE TITLE
StereoPannerNode Converting Stereo Input to right channel mono (Safari)

### ISSUE THREAD

**Issue by ichabodcole** [chrisguttandin/standardized-audio-context#958]
Hi @chrisguttandin, first just want to say thanks a billion for creating this library!

I'm having a bit of trouble getting the StereoPannerNode to give me consistent results across browsers (well, Safari is the issue of course). I have a separate left and right signal I am combining with a ChannelMergerNode, and then running into a StereoPannerNode. In Chrome / Firefox, if the pan value is 0 then these two tones stay separated and there is no perceptual difference, however in Safari it seems that only the right channel is used and is converted to a mono signal spread across both channels.

This may just be my own ignorance as far as settings things up correctly or a limitation of the implementation for Safari, but hoping you could provide feedback on if and how I could resolve the issue.

I have put together a stackblitz demo to illustrate the issue I'm hitting. When you click "start" you should hear a binaural beat (using headphones) created by two slightly offset oscillator frequencies. If you then click "Connect Pan", the signal will be run through a StereoPanNode with a pan value of 0. As noted above in Chrome / Firefox, this creates no perceptual difference and the signal maintain their separation, however in Safari only the right channel's tone will be used and is additionally distributed evenly across both channels. If you comment out the right oscillator (line 44), you won't hear anything in Safari when the StereoPanNode is connected.

Appreciate any guidance you can provide :D

https://stackblitz.com/edit/js-cross-browser-stereo-pan-test-9ad2vn?file=index.js

**Comment by chrisguttandin** [comment]
Hi @ichabodcole,

thanks a lot for that detailed report and the example app to reproduce the problem. In the end I only had to change 4 numbers. The info you provided made it very easy for me to find the bug.

There was a bug in the implementation of the StereoPannerNode. Apparently the left channel wasn't connected at all when having a stereo input. Since Safari is the only browser without a native implementation that bug only surfaced in Safari.

In case you're interested in the inner workings I once wrote an [article which explains how the implementation of the StereoPannerNode works](https://media-codings.com/articles/reimplementing-the-stereo-panner-node).

**Comment by chrisguttandin** [comment]
Version 25.0.4 which should contain the fix is available now on npm.
