### ISSUE TITLE
How can I build es6 or es5 module?

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [chrisguttandin/standardized-audio-context#962]
import es2019 module will throw "Uncaught SyntaxError: Unexpected token { " in some browser, especially those devices with lower browser versions (it happen across chrome, safari).

**Comment by chrisguttandin** [comment]
Hi @Francis-Tao-jinjin,

I know this is annoying but it is somehow expected since older browsers don't fully support the ES2019 syntax. In order to allow applications which only target modern browsers to ship modern JavaScript I chose to publish code which follows the latest stable EcmaScript spec. Unfortunately that also means that you need to transpile it with a tool like Babel if you want to support older browsers as well.

There is no way to un-transpile transpiled code so far which is why I think this is currently the best solution to support both use cases.

To make this work you can either configure your bundler to pick up the ES5 bundle which is linked by the main property of the package.json or you can configure your transpiler to also transpile the code of standardized-audio-context during the build process.

I would love this process to be easier but since I think there is nothing which can be done about it right now I'm going to close this issue. As always, feel free to reopen it if you think there is anything that needs to be discussed any further.
