### ISSUE TITLE
Safari AnalyserNode.getFloatTimeDomainData values limited to [-1, 1]

### ISSUE THREAD

**Issue by tambien** [chrisguttandin/standardized-audio-context#971]
Chrome and Firefox both produce values in any range. Looking at the Web Audio API spec, the range is not defined, so i'd assume that Chrome and FF have the more correct implementation. I filed [a bug](https://github.com/WebAudio/web-audio-api/issues/2296) with the WAA to clarify this.

First i thought, a simple solution to make the behavior consistent would be to attach a gain node on the input to scale the incoming signal by some factor and then multiply the output of getFloatTimeDomainData by the inverse of that factor. After a quick test it seems like the smallest value that Safari can represent before outputting `0` is `1 / 128`, so that doesn't really give us a lot of options for choosing that scaling factor and still accommodating a range of inputs. 

The other solution would be to implement this behavior in an AudioWorklet. 

I thought at the very least, it'd be good to put it on your radar for including in a compatibility test even if there is no obvious solution at the moment.

**Comment by chrisguttandin** [comment]
Hi @tambien, I think this is because `getFloatTimeDomainData()` is not yet supported in Safari and I added a [rather rough polyfill](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/helpers/wrap-analyser-node-get-float-time-domain-data-method.ts) for it. It uses the values returned by `getByteTimeDomainData()` which are clamped [as defined by the spec](https://webaudio.github.io/web-audio-api/#dom-analysernode-getbytetimedomaindata).

I just checked if `getFloatTimeDomainData()` is part of what Safari calls the "Modern WebAudio API". It luckily is and therefore it may land in the next version of Safari.

Until then I guess a `ScriptProcessorNode` (because there is no AudioWorklet yet as well) based polyfill would be the only way to get the exact values. I'm not sure if that will work though. I think it could be tricky to guarantee that the time domain data is gathered from the same piece of audio as the frequency domain data.

Just for reference: We already talked briefly about the issue in Tonejs/Tone.js#129.

**Comment by tambien** [comment]
You're library did such a good job standardizing the WAA that i made me forget just how far behind Safari's implementation is! sorry for the noise! 😳 

IMO it's not worth the effort of implementing it with the script processor since it'll hopefully be arriving soon!
