### ISSUE TITLE
standardized-audio-context is causing garbage collection frequently in Firefox

### ISSUE THREAD

**Issue by kirbysayshi** [chrisguttandin/standardized-audio-context#981]
Hello! As far as I can tell, even with a completely empty graph, standardized-audio-context is creating a script processor node and using it to implement AudioContext.listener. I definitely understand why this would be happening, as listener is an ever-present property on AudioContext.

However, the main issue I'm seeing though is that this processing is causing frequent allocations that later must be garbage collected. In a production application that uses ToneJS (and thus standardized-audio-context), I'm seeing garbage collection take up a significant portion of the frame and audio frame budget in Firefox. And it seems to be mostly coming from standardized-audio-context (even though the app is not doing any spatialization).

To reproduce, I made a very simple codesandbox that:

- creates an AudioContext via standardized-audio-context (and does nothing with it)
- calls react's `setState` every 100ms with a new object and counter int

The results are that over a ~12 second period, standardized-audio-context via `getChannelData` was responsible for 91% of the allocations, while doing "nothing"! Additionally, the amount of CPU expended on standardized-audio-context's processing and the `setState` calls are roughly equivalent. This test of course is slightly unfair, as audio is just a lot larger than an object+counter int, but hopefully this illustrates the issue I'm seeing in production.

Codesandbox: https://codesandbox.io/s/billowing-wind-14xrm?file=/src/App.tsx

A flame graph of allocations for the codesandbox, showing the source and amount:
<img width="1577" alt="Screenshot 2021-07-20 at 11 58 26 AM" src="https://user-images.githubusercontent.com/90831/126365896-4df6d4d9-3ba2-42de-9e32-53a502033dac.png">

One idea I had to address this was to lazily-initialize the ScriptProcessorNode once something actually required spatialization, such as accessing `.listener` or creating a `PannerNode`. What do you think?

**Comment by chrisguttandin** [comment]
Hi @kirbysayshi,

many thanks for your detailed report. You're right, standardized-audio-context was creating the ScriptProcessorNode for the AudioListener right away. I'm not sure though why I did it this way. I was under the impression that it gets initialized lazily and only when needed. Thanks for making me aware of that flaw.

For some reason I can't reproduce the flame graph from above. I don't even see the `getChannelData()` calls in the graph. I'm still on macOS 10.14 and don't have an M1 chip. Maybe Firefox works a bit differently in that case. At least in theory `getChannelData()` could have a very minimal overhead when copying the channelData can be avoided as described by the [acquire the content](https://webaudio.github.io/web-audio-api/#acquire-the-content) algorithm.

In any case using `copyFromChannel()` seems to be more appropriate for the use case. I changed the code to use `copyFromChannel()` if possible. Hopefully that does already reduce the memory pressure. c02323f04b6ee431fb36d82548652f76cdb33239

I also made sure the fake AudioParams for the AudioListener now only get created when one of their scheduling functions gets called. I initially planned to lazily initialize the listener itself but since Tone.js actually [accesses the listener once to copy the params](https://github.com/Tonejs/Tone.js/blob/master/Tone/core/context/Listener.ts) that would not work. b8fa61ad5c52a81f147380ad3de862501eebbdd3

Since I couldn't reproduce the issue could you please double check if the flame graph does now look any better for you (after triggering the listener initialization)?

While making the changes I also noticed that the faked AudioParams never worked when used with an OfflineAudioContext. Consequently they will now throw a `NotSupportedError` instead of failing silently. 19b6fbfee832cf1a62e2a8c8b6affcb13cec9cf8

**Comment by kirbysayshi** [comment]
@chrisguttandin My apologies for the delay in getting back to you.

WOW! 😍 Excellent work! Look at this amazing new baseline flame graph (SPOILER: IT'S ALL REACT NOW!):

![Screenshot 2021-07-28 at 4 07 22 PM](https://user-images.githubusercontent.com/90831/127388885-bf1187e2-1a39-4505-aed0-66cde4ceae3f.png)

And once the listener has been initialized (~12 second profile, just like in the initial report):

![Screenshot 2021-07-28 at 4 17 19 PM](https://user-images.githubusercontent.com/90831/127389877-837079c5-c4a3-4532-bc01-b79a25bcdc41.png)

I believe that's a 1000x improvement in allocations 😄 (previously 1,557,000 bytes, now 1,280 bytes). It's looking great! Truly excellent work!

![Screenshot 2021-07-28 at 4 23 06 PM](https://user-images.githubusercontent.com/90831/127390669-96d87a6d-7776-4008-82fe-e415a058a332.png)


Regarding the profiles themselves, I used the new-ish Firefox Profiler that's built into at least Firefox Developer Edition. There is a button you can add to the toolbar to avoid having the DevTools open. More info here: https://profiler.firefox.com/ It records _a lot_ about the browser, so it can actually be hard to find the profile of the content you're looking for. I usually have to hit "Show all tracks" and then scroll down in the main pane until I find something that looks close to what I'm expecting:

![Screenshot 2021-07-28 at 4 20 45 PM](https://user-images.githubusercontent.com/90831/127390249-20001194-3624-407b-ae8d-67d1574ce27b.png)

Also, I'm not on an M1 mac, it's a 2019 Intel macbook pro, just to rule that out too.

Wow, I'm in awe of this, this is amazing. Thank you so much!

**Comment by chrisguttandin** [comment]
Thanks for reporting back. I'm happy to hear that it works much better now.

Also thanks for letting me know about the new profiler. I saw a demo of it a while ago but somehow missed that it is now available in the Developer Edition of Firefox. I'm going to profile all the things now. :-)
